from __future__ import annotations

# Calendar Tribute License 1.0 — see LICENSE_CALENDAR_TRIBUTE.md

_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#f5f1e8">
<title>Family Calendar · Logical Robot</title>
<style>
:root{--bg:#f5f1e8;--paper:#fffdf8;--ink:#17231d;--muted:#6d796f;--line:#d9ddd4;--soft:#e9eee5;--green:#1f6b4c;--green2:#dcefe4;--amber:#9a6427;--red:#a44747;--shadow:0 18px 60px #24362b18;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink)}body{overflow-x:hidden}button,input,select,textarea{font:inherit}button{touch-action:manipulation}
.shell{min-height:100vh;display:grid;grid-template-rows:auto 1fr}.top{position:sticky;top:0;z-index:50;background:#fffdf8ee;backdrop-filter:blur(18px);border-bottom:1px solid var(--line);padding:max(10px,env(safe-area-inset-top)) 14px 10px}.topline{display:flex;align-items:center;gap:10px}.brand{min-width:220px}.brand h1{font-size:clamp(17px,2vw,24px);margin:0;line-height:1}.brand small{display:block;color:var(--muted);font-size:10px;margin-top:5px}.mark{display:inline-grid;place-items:center;width:26px;height:26px;border-radius:9px;background:var(--green);color:white;margin-right:7px;font-size:14px}.nav{display:flex;gap:6px;align-items:center;flex:1}.spacer{flex:1}.btn,.view{border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:12px;min-height:42px;padding:8px 12px;font-weight:720;cursor:pointer}.btn:hover,.view:hover{background:#f0f4ec}.btn.primary{background:var(--green);border-color:var(--green);color:white}.btn.icon{min-width:42px;padding:7px}.viewbar{display:flex;gap:6px;overflow-x:auto;padding-top:9px;scrollbar-width:none}.viewbar::-webkit-scrollbar{display:none}.view{white-space:nowrap;min-height:38px;font-size:11px}.view.active{background:var(--ink);border-color:var(--ink);color:white}.dateTitle{font-weight:800;font-size:13px;white-space:nowrap}
.main{display:grid;grid-template-columns:230px minmax(0,1fr);min-height:0}.side{border-right:1px solid var(--line);background:#faf8f2;padding:14px;overflow:auto}.side h3{font-size:10px;text-transform:uppercase;letter-spacing:.13em;color:var(--muted);margin:13px 0 8px}.side h3:first-child{margin-top:0}.person{display:flex;align-items:center;gap:8px;padding:9px;border-radius:11px;cursor:pointer}.person:hover{background:var(--soft)}.dot{width:12px;height:12px;border-radius:50%;background:var(--green);box-shadow:inset 0 0 0 2px #fff}.person span{font-size:12px;font-weight:700}.tiny{font-size:9px;color:var(--muted);line-height:1.45}.axis{display:grid;grid-template-columns:26px 1fr;gap:7px;align-items:center;margin-bottom:7px}.axis b{font-size:10px}.axis select{border:1px solid var(--line);border-radius:9px;background:white;padding:8px;font-size:10px;min-width:0}.license{margin-top:18px;border-top:1px solid var(--line);padding-top:11px;color:var(--muted);font-size:8.5px;line-height:1.5}.license strong{color:var(--ink)}
.stage{position:relative;min-width:0;overflow:auto;padding:12px}.card{background:var(--paper);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow)}.empty{display:grid;place-items:center;min-height:50vh;text-align:center;color:var(--muted);padding:30px}.empty b{display:block;color:var(--ink);font-size:20px;margin-bottom:7px}.empty .btn{margin-top:13px}
.timeline{display:grid;grid-template-columns:54px repeat(var(--days),minmax(145px,1fr));min-width:700px}.timeHead{height:52px;border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--paper);z-index:10}.dayHead{height:52px;border-left:1px solid var(--line);border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--paper);z-index:10;padding:9px 10px}.dayHead b{display:block;font-size:12px}.dayHead span{font-size:9px;color:var(--muted)}.timeRail{position:relative;height:952px;background:#faf8f2}.hour{position:absolute;left:0;right:0;height:1px;border-top:1px solid #e7e8e2;font-size:9px;color:var(--muted);padding-left:4px}.dayCol{position:relative;height:952px;border-left:1px solid var(--line);background:repeating-linear-gradient(to bottom,transparent 0,transparent 58.5px,#eef0ea 59px,#eef0ea 59.5px)}.dayCol.today{background-color:#f3f8f3}.event{position:absolute;left:5px;right:5px;min-height:34px;border:1px solid #8eb29f;background:#deeee4;border-radius:10px;padding:7px 8px;overflow:hidden;cursor:grab;touch-action:none;z-index:5;box-shadow:0 4px 12px #23452e16}.event:active{cursor:grabbing}.event.dragging{opacity:.62;transform:scale(1.02);z-index:30}.event.conflict{border-color:#cc8c8c;background:#f5dddd}.event b{font-size:10.5px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.event small{font-size:8.5px;color:#4d695a}.event .chips{margin-top:4px;display:flex;gap:3px;flex-wrap:wrap}.chip{font-size:7.5px;padding:2px 5px;border-radius:999px;background:#fff8;border:1px solid #9fb6a9}.nowline{position:absolute;left:0;right:0;border-top:2px solid #d56161;z-index:8;pointer-events:none}
.month{display:grid;grid-template-columns:repeat(7,minmax(118px,1fr));min-width:760px;overflow:hidden}.monthDow{padding:10px;font-size:9px;color:var(--muted);font-weight:800;text-transform:uppercase;border-bottom:1px solid var(--line)}.dayCell{min-height:128px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:7px;background:var(--paper)}.dayCell.out{opacity:.45}.dayCell.today{background:#f1f7f1}.dayNum{font-size:10px;font-weight:800;margin-bottom:5px}.monthEvent{font-size:8.5px;padding:5px 6px;border-radius:7px;background:var(--green2);margin:3px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:grab;touch-action:none}.monthEvent.conflict{background:#f4dada}
.year{display:grid;grid-template-columns:repeat(4,minmax(190px,1fr));gap:10px}.miniMonth{padding:11px}.miniMonth h3{margin:0 0 8px;font-size:12px}.miniGrid{display:grid;grid-template-columns:repeat(7,1fr);gap:2px}.miniDay{aspect-ratio:1;display:grid;place-items:center;border-radius:7px;font-size:8px;position:relative}.miniDay.has{background:var(--green2);font-weight:800}.miniDay.today{box-shadow:inset 0 0 0 1px var(--green)}
.personLanes{display:grid;gap:9px}.lane{display:grid;grid-template-columns:150px 1fr;min-height:92px;overflow:hidden}.laneName{padding:14px;border-right:1px solid var(--line);font-weight:800}.laneEvents{display:flex;align-items:stretch;gap:7px;padding:9px;overflow-x:auto;min-width:0}.laneCard{min-width:180px;max-width:260px;border:1px solid #b7c9bc;background:#edf5ef;border-radius:11px;padding:10px;cursor:grab;touch-action:none}.laneCard b{font-size:11px}.laneCard small{display:block;color:var(--muted);font-size:8.5px;margin-top:4px}
.eventList{display:grid;gap:8px}.eventRow{display:grid;grid-template-columns:120px minmax(180px,1fr) 1fr auto;gap:10px;align-items:center;padding:12px}.eventRow .when{font-size:10px;font-weight:800}.eventRow .title{font-weight:800}.eventRow .meta{font-size:9px;color:var(--muted)}
.dimWrap{display:grid;gap:10px}.dimIntro{padding:14px}.dimIntro h2{margin:0 0 5px;font-size:18px}.dimIntro p{margin:0;color:var(--muted);font-size:10px}.dimBoard{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:9px}.dimCard{padding:12px;min-height:120px}.dimCoords{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.coord{font-size:8px;border:1px solid var(--line);border-radius:999px;padding:4px 6px}.coord strong{color:var(--green)}
.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#17231de9;color:white;border-radius:12px;padding:10px 14px;font-size:10px;z-index:100;display:none}.modalBack{position:fixed;inset:0;background:#17231d55;z-index:90;display:none;align-items:flex-end;justify-content:center;padding:12px}.modal{width:min(620px,100%);background:var(--paper);border-radius:20px;padding:18px;box-shadow:0 30px 90px #17231d55;max-height:90vh;overflow:auto}.modal h2{margin:0 0 12px;font-size:20px}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{display:grid;gap:5px}.field.full{grid-column:1/-1}.field label{font-size:9px;color:var(--muted);font-weight:800}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line);background:white;border-radius:11px;min-height:44px;padding:9px;color:var(--ink)}.peopleChecks{display:flex;gap:6px;flex-wrap:wrap}.peopleChecks label{border:1px solid var(--line);border-radius:999px;padding:8px 10px;font-size:10px}.modalActions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.qcds{margin-top:10px;border:1px solid #bdd0c2;background:#edf6ef;border-radius:12px;padding:10px;font-size:9px}.qcds b{font-size:10px}.qcdsRows{display:grid;gap:4px;margin-top:6px}.qrow{display:grid;grid-template-columns:90px 1fr 44px;align-items:center;gap:7px}.bar{height:7px;background:#d7e3d9;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:var(--green)}
@media(max-width:1050px){.main{grid-template-columns:1fr}.side{display:none}.year{grid-template-columns:repeat(3,minmax(180px,1fr))}.brand small{display:none}}
@media(max-width:680px){.top{padding-left:9px;padding-right:9px}.topline{flex-wrap:wrap}.brand{min-width:0;flex:1}.brand h1{font-size:17px}.nav{order:3;width:100%}.dateTitle{flex:1;text-align:center}.stage{padding:7px}.timeline{min-width:640px}.year{grid-template-columns:1fr}.month{min-width:700px}.eventRow{grid-template-columns:92px 1fr auto}.eventRow .meta{grid-column:1/-1}.formGrid{grid-template-columns:1fr}.field.full{grid-column:auto}.modalBack{padding:0}.modal{border-radius:20px 20px 0 0}.view{min-height:42px}.btn{min-height:44px}}
@media(min-width:1700px){:root{font-size:18px}.main{grid-template-columns:280px 1fr}.timeline{grid-template-columns:70px repeat(var(--days),minmax(190px,1fr))}.dayCol,.timeRail{height:1120px}.event b{font-size:12px}.month{grid-template-columns:repeat(7,1fr)}.dayCell{min-height:170px}}
</style>
</head>
<body>
<div class="shell">
<header class="top">
  <div class="topline">
    <div class="brand"><h1><span class="mark">◇</span>Family Calendar</h1><small>Logical Robot · one Calendar Space · QCDS / Syntract</small></div>
    <div class="nav">
      <button class="btn icon" id="prevBtn" aria-label="Previous">‹</button>
      <button class="btn" id="todayBtn">Today</button>
      <button class="btn icon" id="nextBtn" aria-label="Next">›</button>
      <div class="dateTitle" id="dateTitle">Calendar Space</div>
      <div class="spacer"></div>
      <button class="btn" id="personBtn">+ Person</button>
      <button class="btn primary" id="eventBtn">+ Event</button>
    </div>
  </div>
  <div class="viewbar" id="viewbar">
    <button class="view" data-view="day">Day</button><button class="view active" data-view="week">Week</button><button class="view" data-view="month">Month</button><button class="view" data-view="year">Year</button><button class="view" data-view="person">Person</button><button class="view" data-view="event">Event</button><button class="view" data-view="dimension">Dimension X · Y · Z</button>
  </div>
</header>
<div class="main">
  <aside class="side">
    <h3>People in this space</h3><div id="peopleList"></div>
    <h3>Dimension axes</h3>
    <div class="axis"><b>X</b><select id="axisX"></select></div><div class="axis"><b>Y</b><select id="axisY"></select></div><div class="axis"><b>Z</b><select id="axisZ"></select></div>
    <div class="tiny">Axes change the perspective, not the source of truth. Every event remains one state in the same Calendar Space.</div>
    <div class="license"><strong>Calendar Tribute License 1.0</strong><br>Personal / household use free. Academic use free with Tribute. Organizational use EUR 99/month or EUR 990/year.</div>
  </aside>
  <main class="stage" id="stage"></main>
</div>
</div>
<div class="toast" id="toast"></div>
<div class="modalBack" id="modalBack"><div class="modal" role="dialog" aria-modal="true">
  <h2 id="modalTitle">New event</h2>
  <div class="formGrid">
    <div class="field full"><label>Title</label><input id="fTitle" placeholder="Football, dinner, school…"></div>
    <div class="field"><label>Starts</label><input id="fStart" type="datetime-local"></div>
    <div class="field"><label>Ends</label><input id="fEnd" type="datetime-local"></div>
    <div class="field full"><label>Location</label><input id="fLocation" placeholder="Optional"></div>
    <div class="field full"><label>People</label><div class="peopleChecks" id="fPeople"></div></div>
    <div class="field"><label>Dimension name</label><input id="fDimKey" placeholder="activity"></div>
    <div class="field"><label>Dimension value</label><input id="fDimValue" placeholder="sport"></div>
  </div>
  <div id="qcdsBox"></div>
  <div class="modalActions"><button class="btn" id="closeModal">Cancel</button><button class="btn" id="inferBtn">QCDS fit</button><button class="btn primary" id="saveEvent">Save</button></div>
</div></div>
<script>
const state={data:null,view:'week',anchor:startOfDay(new Date()),selected:null,drag:null};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function pad(n){return String(n).padStart(2,'0')} function localIso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function startOfDay(d){const x=new Date(d);x.setHours(0,0,0,0);return x} function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x} function addMonths(d,n){const x=new Date(d);x.setMonth(x.getMonth()+n);return x}
function monday(d){const x=startOfDay(d),day=(x.getDay()+6)%7;return addDays(x,-day)} function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function fmtDate(d,opt={weekday:'short',day:'numeric',month:'short'}){return new Intl.DateTimeFormat(undefined,opt).format(d)} function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});const j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function toast(msg){const e=$('#toast');e.textContent=msg;e.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display='none',2400)}
function personName(id){return state.data?.people.find(p=>p.person_id===id)?.name||id} function conflictsFor(id){return (state.data?.conflicts||[]).some(c=>c.left_event_id===id||c.right_event_id===id)}
async function load(){state.data=await api('/api/state');populateAxes();renderPeople();render();}
function populateAxes(){const keys=Object.keys(state.data?.dimensions||{}),defaults=['person','day','location'];[['#axisX',defaults[0]],['#axisY',defaults[1]],['#axisZ',defaults[2]]].forEach(([sel,def])=>{const e=$(sel),old=e.value;e.innerHTML=keys.map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('');e.value=keys.includes(old)?old:(keys.includes(def)?def:(keys[0]||''));});}
function renderPeople(){const box=$('#peopleList'),people=state.data?.people||[];box.innerHTML=people.length?people.map(p=>`<div class="person" data-person="${esc(p.person_id)}"><i class="dot"></i><span>${esc(p.name)}</span></div>`).join(''):'<div class="tiny">No people yet. Add a person, then place events in the shared Calendar Space.</div>';}
function setTitle(){const a=state.anchor;if(state.view==='week'){const m=monday(a),e=addDays(m,6);$('#dateTitle').textContent=`${fmtDate(m,{day:'numeric',month:'short'})} – ${fmtDate(e,{day:'numeric',month:'short',year:'numeric'})}`;}else if(state.view==='month')$('#dateTitle').textContent=fmtDate(a,{month:'long',year:'numeric'});else if(state.view==='year')$('#dateTitle').textContent=String(a.getFullYear());else $('#dateTitle').textContent=fmtDate(a,{weekday:'long',day:'numeric',month:'long',year:'numeric'});}
function render(){setTitle();$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===state.view));if(!(state.data?.events||[]).length){$('#stage').innerHTML=`<div class="card empty"><div><b>Calendar Space is empty</b><span>Add people and events. They will all live in the same logical space.</span><br><button class="btn primary" onclick="openEvent()">Create first event</button></div></div>`;return;}({day:renderTimeline,week:renderTimeline,month:renderMonth,year:renderYear,person:renderPerson,event:renderEventList,dimension:renderDimensions}[state.view]||renderTimeline)();bindDrags();}
function visibleDays(){if(state.view==='day')return [startOfDay(state.anchor)];const m=monday(state.anchor);return Array.from({length:7},(_,i)=>addDays(m,i));}
function dayEvents(day){return state.data.events.filter(e=>sameDay(new Date(e.start),day)).sort((a,b)=>new Date(a.start)-new Date(b.start));}
function eventHtml(e,day){const s=new Date(e.start),en=new Date(e.end),top=((s.getHours()+s.getMinutes()/60)-6)*59.5,dur=(en-s)/3600000,height=Math.max(34,dur*59.5-3);if(top<0||top>952)return '';return `<div class="event ${conflictsFor(e.event_id)?'conflict':''}" data-event-id="${esc(e.event_id)}" style="top:${top}px;height:${height}px"><b>${esc(e.title)}</b><small>${pad(s.getHours())}:${pad(s.getMinutes())} · ${e.people.map(personName).map(esc).join(', ')||'Everyone'}</small>${e.location?`<div class="chips"><span class="chip">${esc(e.location)}</span></div>`:''}</div>`;}
function renderTimeline(){const days=visibleDays(),today=new Date(),heads=days.map(d=>`<div class="dayHead"><b>${fmtDate(d,{weekday:'short',day:'numeric'})}</b><span>${fmtDate(d,{month:'short'})}</span></div>`).join(''),hours=Array.from({length:17},(_,i)=>`<div class="hour" style="top:${i*59.5}px">${pad(i+6)}:00</div>`).join(''),cols=days.map(d=>`<div class="dayCol ${sameDay(d,today)?'today':''}" data-drop-date="${localIso(d).slice(0,10)}">${dayEvents(d).map(e=>eventHtml(e,d)).join('')}${sameDay(d,today)?nowLine():''}</div>`).join('');$('#stage').innerHTML=`<div class="card timeline" style="--days:${days.length}"><div class="timeHead"></div>${heads}<div class="timeRail">${hours}</div>${cols}</div>`;}
function nowLine(){const n=new Date(),top=((n.getHours()+n.getMinutes()/60)-6)*59.5;return top>=0&&top<=952?`<div class="nowline" style="top:${top}px"></div>`:''}
function renderMonth(){const a=new Date(state.anchor.getFullYear(),state.anchor.getMonth(),1),start=monday(a),today=new Date(),dow=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="monthDow">${x}</div>`).join(''),cells=Array.from({length:42},(_,i)=>{const d=addDays(start,i),ev=dayEvents(d);return `<div class="dayCell ${d.getMonth()!==a.getMonth()?'out':''} ${sameDay(d,today)?'today':''}" data-drop-date="${localIso(d).slice(0,10)}"><div class="dayNum">${d.getDate()}</div>${ev.slice(0,5).map(e=>`<div class="monthEvent ${conflictsFor(e.event_id)?'conflict':''}" data-event-id="${esc(e.event_id)}">${esc(e.title)}</div>`).join('')}${ev.length>5?`<div class="tiny">+${ev.length-5} more</div>`:''}</div>`}).join('');$('#stage').innerHTML=`<div class="card month">${dow}${cells}</div>`;}
function renderYear(){const y=state.anchor.getFullYear(),today=new Date();$('#stage').innerHTML=`<div class="year">${Array.from({length:12},(_,m)=>{const first=new Date(y,m,1),st=monday(first),days=Array.from({length:42},(_,i)=>{const d=addDays(st,i),has=dayEvents(d).length>0;return `<div class="miniDay ${has?'has':''} ${sameDay(d,today)?'today':''}" style="opacity:${d.getMonth()===m?1:.25}">${d.getDate()}</div>`}).join('');return `<div class="card miniMonth"><h3>${fmtDate(first,{month:'long'})}</h3><div class="miniGrid">${days}</div></div>`}).join('')}</div>`;}
function renderPerson(){const people=state.data.people;$('#stage').innerHTML=`<div class="personLanes">${people.map(p=>{const ev=state.data.events.filter(e=>e.people.includes(p.person_id)).sort((a,b)=>new Date(a.start)-new Date(b.start));return `<div class="card lane" data-drop-person="${esc(p.person_id)}"><div class="laneName">${esc(p.name)}</div><div class="laneEvents">${ev.length?ev.map(e=>`<div class="laneCard" data-event-id="${esc(e.event_id)}"><b>${esc(e.title)}</b><small>${esc(fmtDate(new Date(e.start),{weekday:'short',day:'numeric',month:'short'}))} · ${pad(new Date(e.start).getHours())}:${pad(new Date(e.start).getMinutes())}</small></div>`).join(''):'<span class="tiny">No events</span>'}</div></div>`}).join('')}</div>`;}
function renderEventList(){const rows=state.data.events.map(e=>{const s=new Date(e.start);return `<div class="card eventRow"><div class="when">${esc(fmtDate(s,{weekday:'short',day:'numeric',month:'short'}))}<br>${pad(s.getHours())}:${pad(s.getMinutes())}</div><div><div class="title">${esc(e.title)}</div><div class="meta">${e.people.map(personName).map(esc).join(', ')||'No person'}${e.location?' · '+esc(e.location):''}</div></div><div class="meta">${Object.entries(e.dimensions||{}).map(([k,v])=>`${esc(k)}=${esc(v)}`).join(' · ')}</div><button class="btn" onclick="openEvent('${esc(e.event_id)}')">Open</button></div>`}).join('');$('#stage').innerHTML=`<div class="eventList">${rows}</div>`;}
function dimValue(e,key){if(key==='person')return e.people.map(personName).join(', ')||'—';if(key==='day')return localIso(new Date(e.start)).slice(0,10);if(key==='location')return e.location||'—';if(key==='event')return e.title;return (e.dimensions||{})[key]??'—'}
function renderDimensions(){const x=$('#axisX').value,y=$('#axisY').value,z=$('#axisZ').value;$('#stage').innerHTML=`<div class="dimWrap"><div class="card dimIntro"><h2>Calendar Space · X / Y / Z</h2><p>One state space, projected through <b>${esc(x||'X')}</b>, <b>${esc(y||'Y')}</b> and <b>${esc(z||'Z')}</b>. Change axes at left.</p></div><div class="dimBoard">${state.data.events.map(e=>`<div class="card dimCard"><b>${esc(e.title)}</b><div class="dimCoords"><span class="coord"><strong>X</strong> ${esc(x)}: ${esc(dimValue(e,x))}</span><span class="coord"><strong>Y</strong> ${esc(y)}: ${esc(dimValue(e,y))}</span><span class="coord"><strong>Z</strong> ${esc(z)}: ${esc(dimValue(e,z))}</span></div><div class="tiny" style="margin-top:10px">${esc(e.start)} → ${esc(e.end)}</div></div>`).join('')}</div></div>`;}
function bindDrags(){$$('[data-event-id]').forEach(el=>{el.addEventListener('pointerdown',dragStart);});}
function dragStart(ev){if(ev.button!==undefined&&ev.button!==0)return;const el=ev.currentTarget,id=el.dataset.eventId,item=state.data.events.find(x=>x.event_id===id);if(!item||item.locked)return;state.drag={id,el,x:ev.clientX,y:ev.clientY};el.classList.add('dragging');el.setPointerCapture?.(ev.pointerId);el.addEventListener('pointerup',dragEnd,{once:true});el.addEventListener('pointercancel',dragCancel,{once:true});}
async function dragEnd(ev){const d=state.drag;if(!d)return;d.el.classList.remove('dragging');const under=document.elementFromPoint(ev.clientX,ev.clientY),dateCell=under?.closest('[data-drop-date]'),personLane=under?.closest('[data-drop-person]'),item=state.data.events.find(x=>x.event_id===d.id);state.drag=null;if(!item)return;try{let start=new Date(item.start),end=new Date(item.end),duration=end-start,people=[...item.people];if(dateCell){const parts=dateCell.dataset.dropDate.split('-').map(Number);start.setFullYear(parts[0],parts[1]-1,parts[2]);if(dateCell.classList.contains('dayCol')){const r=dateCell.getBoundingClientRect(),minutes=Math.max(0,Math.min(16*60,Math.round(((ev.clientY-r.top)/59.5*60)/15)*15));start.setHours(6+Math.floor(minutes/60),minutes%60,0,0);}end=new Date(start.getTime()+duration);}if(personLane){const pid=personLane.dataset.dropPerson;people=[pid];}if(!dateCell&&!personLane){openEvent(d.id);return;}await api('/api/event/move',{method:'POST',body:JSON.stringify({event_id:d.id,start:localIso(start),end:localIso(end),people})});await load();toast('Event moved in Calendar Space');}catch(e){toast(e.message);}}
function dragCancel(){if(state.drag)state.drag.el.classList.remove('dragging');state.drag=null}
function openEvent(id=null){state.selected=id;const e=id?state.data.events.find(x=>x.event_id===id):null,$m=$('#modalBack');$('#modalTitle').textContent=e?'Event state':'New event';$('#fTitle').value=e?.title||'';let s=e?new Date(e.start):new Date(),en=e?new Date(e.end):new Date(s.getTime()+3600000);if(!e){s.setMinutes(Math.ceil(s.getMinutes()/15)*15,0,0);en=new Date(s.getTime()+3600000)}$('#fStart').value=localIso(s);$('#fEnd').value=localIso(en);$('#fLocation').value=e?.location||'';const dims=Object.entries(e?.dimensions||{});$('#fDimKey').value=dims[0]?.[0]||'';$('#fDimValue').value=dims[0]?.[1]||'';$('#fPeople').innerHTML=(state.data.people||[]).map(p=>`<label><input type="checkbox" value="${esc(p.person_id)}" ${e?.people.includes(p.person_id)?'checked':''}> ${esc(p.name)}</label>`).join('')||'<span class="tiny">Add a person first, or save this as a shared/unassigned event.</span>';$('#qcdsBox').innerHTML='';$m.style.display='flex';}
function closeModal(){$('#modalBack').style.display='none';state.selected=null}
async function saveEvent(){try{const key=$('#fDimKey').value.trim(),val=$('#fDimValue').value.trim(),payload={event_id:state.selected||undefined,title:$('#fTitle').value||'Untitled event',start:$('#fStart').value,end:$('#fEnd').value,location:$('#fLocation').value,people:$$('#fPeople input:checked').map(x=>x.value),dimensions:key?{[key]:val}:{}};await api('/api/event',{method:'POST',body:JSON.stringify(payload)});closeModal();await load();toast('Event saved as Calendar Space state');}catch(e){toast(e.message)}}
async function inferFit(){if(!state.selected){toast('Save the event first, then ask QCDS about placement');return}try{$('#inferBtn').disabled=true;const r=await api('/api/infer',{method:'POST',body:JSON.stringify({event_id:state.selected})});$('#qcdsBox').innerHTML=`<div class="qcds"><b>QCDS placement projection · ${r.logical_width} Conditions · 2^${r.logical_width} raw states</b><div class="tiny">Same SyntractSystem; existing events act as represented placement constraints.</div><div class="qcdsRows">${r.stabilized.map(x=>`<div class="qrow"><span>${esc(x.value)}</span><div class="bar"><i style="width:${Math.max(1,x.probability*100)}%"></i></div><b>${(x.probability*100).toFixed(1)}%</b></div>`).join('')}</div></div>`;}catch(e){toast(e.message)}finally{$('#inferBtn').disabled=false}}
async function addPerson(){const name=prompt('Person name');if(!name)return;try{await api('/api/person',{method:'POST',body:JSON.stringify({name})});await load();toast('Person added to Calendar Space')}catch(e){toast(e.message)}}
function shift(dir){if(state.view==='day')state.anchor=addDays(state.anchor,dir);else if(state.view==='week'||state.view==='person'||state.view==='event'||state.view==='dimension')state.anchor=addDays(state.anchor,dir*7);else if(state.view==='month')state.anchor=addMonths(state.anchor,dir);else state.anchor=new Date(state.anchor.getFullYear()+dir,state.anchor.getMonth(),1);render()}
$('#viewbar').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;render()});$('#prevBtn').onclick=()=>shift(-1);$('#nextBtn').onclick=()=>shift(1);$('#todayBtn').onclick=()=>{state.anchor=startOfDay(new Date());render()};$('#eventBtn').onclick=()=>openEvent();$('#personBtn').onclick=addPerson;$('#closeModal').onclick=closeModal;$('#saveEvent').onclick=saveEvent;$('#inferBtn').onclick=inferFit;$('#modalBack').addEventListener('click',e=>{if(e.target===$('#modalBack'))closeModal()});['#axisX','#axisY','#axisZ'].forEach(s=>$(s).addEventListener('change',()=>{if(state.view==='dimension')renderDimensions()}));
load().catch(e=>{$('#stage').innerHTML=`<div class="card empty"><div><b>Calendar runtime unavailable</b><span>${esc(e.message)}</span></div></div>`});
</script>
</body>
</html>'''


def calendar_robot_html() -> str:
    return _HTML


__all__ = ["calendar_robot_html"]
