from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence


_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#07101a">
<title>The Logical Robot — Intelligence Growth</title>
<style>
:root{color-scheme:dark;--bg:#06101a;--panel:#0a1825;--panel2:#0d2030;--line:#23445a;--text:#eef8ff;--muted:#8fa9bb;--good:#79e5a7;--good2:#b7ffd0;--warn:#f2bd72;--hot:#ff839c;--accent:#70c9ff;--rule:#c7a9ff;--shadow:#0006;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text)}body{background:radial-gradient(circle at 10% -10%,#173c56 0,#081522 34%,#050b12 77%);overflow-x:hidden}button,input,textarea,select{font:inherit}
header{display:flex;align-items:center;gap:15px;padding:17px 22px;border-bottom:1px solid #1d3548;background:#07131ee8;backdrop-filter:blur(14px);position:sticky;top:0;z-index:40}.brand{min-width:270px}.brand h1{font-size:19px;margin:0}.brand small{color:var(--muted);font-size:11px}.pulse{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--good);box-shadow:0 0 18px var(--good);margin-right:8px}.statusbar{display:flex;gap:7px;flex:1;flex-wrap:wrap}.pill{font-size:10px;padding:6px 9px;border:1px solid #2d4a60;border-radius:999px;background:#0c1c29;color:#aac1d0}.pill.live{border-color:#337850;color:#aef4c7}.pill.degraded{border-color:#795e33;color:#f2ca88}.pill.recorded{border-color:#66517f;color:#d9c5ff}.connect{display:flex;gap:6px;min-width:320px}.connect input{min-width:220px}
button{border:1px solid #31536b;background:#102638;color:#edf8ff;border-radius:9px;padding:9px 11px;font-weight:720;font-size:10px;letter-spacing:.02em;cursor:pointer}button:hover{filter:brightness(1.12)}button.primary{background:#d9f8e4;border-color:#d9f8e4;color:#082117}button.heroButton{background:linear-gradient(135deg,#d8f8e3,#9ceec0);border:0;color:#062016;font-size:11px;padding:11px 14px;box-shadow:0 0 24px #79e5a722}button:disabled{opacity:.45;cursor:wait}.warnButton{border-color:#775d33;color:#f4cf8d}select,input,textarea{width:100%;background:#07131e;color:#eaf6ff;border:1px solid #2e4d64;border-radius:9px;padding:9px;font-size:11px}textarea{min-height:78px;resize:vertical}
.hero{padding:14px 14px 0;max-width:1800px;margin:auto}.growthHero{border:1px solid #2b5265;background:linear-gradient(135deg,#0b1b28ee,#0b1925e8 58%,#0e211cdd);border-radius:18px;box-shadow:0 18px 60px var(--shadow);overflow:hidden}.growthTop{display:flex;align-items:center;gap:15px;padding:15px 18px;border-bottom:1px solid #1e394b}.growthTitle{flex:1}.eyebrow{font-size:9px;letter-spacing:.18em;color:#82a2b7;text-transform:uppercase}.growthTitle h2{font-size:21px;margin:3px 0 2px}.growthTitle p{margin:0;color:#91aabb;font-size:11px}.growthActions{display:flex;gap:7px;flex-wrap:wrap}.stages{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:#1a3547}.stage{background:#0a1925;padding:11px 14px;min-height:71px}.stage .stageName{font-size:8px;text-transform:uppercase;letter-spacing:.13em;color:#7896aa}.stage b{display:block;font-size:24px;margin-top:3px}.stage small{font-size:9px;color:#829bae}.flow{padding:8px 15px;background:#081722;color:#88a4b6;font-size:9px;letter-spacing:.04em;text-align:center}.flow strong{color:#b9f6ce}.promotion{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(400px,1.2fr);gap:1px;background:#1d3c4c}.promotionMain,.beforeAfter{background:#091924;padding:15px 17px;min-height:150px}.promotionMain.good{background:radial-gradient(circle at 10% 0,#17382d 0,#0a1d20 55%,#091924 100%)}.promotionFlag{font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:#809fb2}.promotionFlag.good{color:var(--good2)}.ruleText{font-size:24px;font-weight:780;margin:8px 0 5px;color:#eefaff;word-break:break-word}.ruleText .arrow{color:var(--good)}.promotionMeta{color:#91acbd;font-size:10px;line-height:1.55}.noLogic{font-size:16px;font-weight:730;margin-top:8px;color:#d4e7f3}.beforeAfter h3{font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#809fb2;margin:0 0 9px}.baGrid{display:grid;grid-template-columns:1fr 38px 1fr;gap:7px;align-items:stretch}.ba{border:1px solid #294a60;background:#0c2030;border-radius:11px;padding:10px}.ba.after{border-color:#367956;background:#0c241d}.ba label{display:block;font-size:8px;color:#829daf;text-transform:uppercase;letter-spacing:.1em}.ba b{display:block;font-size:17px;margin-top:4px}.ba p{font-size:9px;color:#8fa8b9;margin:5px 0 0;line-height:1.4}.baArrow{display:grid;place-items:center;color:var(--good);font-size:22px}.gainline{font-size:9px;color:#94adbd;margin-top:8px}.gainline strong{color:var(--good2)}
.layout{display:grid;grid-template-columns:280px minmax(520px,1fr) 345px;gap:12px;padding:12px 14px 16px;max-width:1800px;margin:auto}.panel{border:1px solid var(--line);background:#091724e9;border-radius:15px;overflow:hidden;box-shadow:0 14px 45px #0004}.panelTitle{font-size:9px;text-transform:uppercase;letter-spacing:.16em;color:#91adbf;padding:13px 14px 10px;border-bottom:1px solid #1d3447}.left,.right{max-height:860px;overflow:auto}.section{padding:12px 13px;border-bottom:1px solid #162d3e}.section:last-child{border:0}.section h3{font-size:9px;text-transform:uppercase;letter-spacing:.12em;color:#839fb2;margin:0 0 9px}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:7px}.metric{background:#0c2030;border:1px solid #244359;border-radius:10px;padding:9px}.metric b{font-size:19px;display:block}.metric span{font-size:8px;color:#91a9ba;text-transform:uppercase;letter-spacing:.04em}.mode{display:flex;align-items:center;justify-content:space-between;padding:7px 0;border-bottom:1px solid #142a39;font-size:11px}.mode:last-child{border:0}.switch{appearance:none;width:34px;height:18px;background:#293b48;border-radius:20px;position:relative;cursor:pointer}.switch:after{content:"";position:absolute;width:14px;height:14px;left:2px;top:2px;border-radius:50%;background:#8093a0;transition:.15s}.switch:checked{background:#265e43}.switch:checked:after{left:18px;background:#aaf4c4}.actions{display:flex;gap:6px;flex-wrap:wrap}.row{display:flex;gap:7px}.row>*{flex:1}.hint{font-size:9px;line-height:1.5;color:#819bad;margin-top:7px}.notice{padding:8px 9px;border-radius:9px;background:#0b1f2d;border:1px solid #28495f;font-size:9px;color:#99b1c0;margin-top:8px}.notice.good{border-color:#2e6748;color:#a8edc0}.notice.warn{border-color:#71582f;color:#edc986}
.center{display:grid;grid-template-rows:auto minmax(430px,1fr) 105px;min-height:720px}.spaceHead{display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid #1c3548}.spaceHead b{font-size:11px}.spaceHead input{max-width:235px}.spaceHead .spacer{flex:1}.graphWrap{position:relative;min-height:0;background:radial-gradient(circle at center,#0b2030 0,#07131d 48%,#050c12 100%)}#graph{width:100%;height:100%;display:block;touch-action:none}.edge{stroke:#375466;stroke-opacity:.43;stroke-width:1}.edge.rule{stroke:var(--rule);stroke-opacity:.78;stroke-width:2}.node circle{fill:#173b51;stroke:#75b9de;stroke-width:1.2}.node.rule circle{fill:#33284a;stroke:#c3a6f5}.node.new circle{stroke:var(--good);stroke-width:3;filter:drop-shadow(0 0 6px #7ee0a3)}.node.focus circle{stroke:#fff1a3;stroke-width:3}.node text{fill:#d6e8f3;font-size:9px;pointer-events:none;text-anchor:middle}.legend{position:absolute;left:10px;bottom:10px;background:#07131ed9;border:1px solid #274357;border-radius:9px;padding:7px 9px;font-size:8px;color:#9ab0bf}.graphEmpty{position:absolute;inset:0;display:none;place-items:center;text-align:center;color:#7593a7;font-size:11px;padding:40px;pointer-events:none}.detail{position:absolute;right:10px;top:10px;max-width:300px;background:#07131ef2;border:1px solid #31526a;border-radius:10px;padding:10px;font-size:9px;line-height:1.45;display:none}.growthChart{padding:7px 12px;border-top:1px solid #1c3548}.growthChartHead{font-size:9px;color:#8ba6b8;margin-bottom:2px}.growthChart svg{width:100%;height:70px}.growthChart polyline{fill:none;stroke:#73c8ff;stroke-width:2}.growthChart .rules{stroke:#c6a4ff}.growthChart text{fill:#7390a5;font-size:8px}
.timeline{display:flex;flex-direction:column;gap:7px}.event{border-left:3px solid #456b83;background:#0a1d2a;border-radius:8px;padding:8px}.event.good{border-color:var(--good)}.event.warn{border-color:var(--warn)}.event.hot{border-color:var(--hot)}.event .meta{font-size:8px;color:#6f8da2}.event b{font-size:10px}.event pre{font-size:8px;color:#9db5c5;white-space:pre-wrap;word-break:break-word;margin:4px 0 0;max-height:100px;overflow:auto}.frontierItem{padding:8px;border:1px solid #244157;background:#0b1d2a;border-radius:9px;margin-bottom:6px}.frontierItem .kind{font-size:8px;text-transform:uppercase;color:#8fa9bb}.frontierItem .goal{font-size:10px;margin-top:3px}.frontierItem .state{font-size:8px;color:#7ee0a3;margin-top:4px}.empty{padding:12px;color:#718da1;font-size:10px;text-align:center}.hidden{display:none!important}
@media(max-width:1200px){.layout{grid-template-columns:250px 1fr}.right{grid-column:1/-1;max-height:none;display:grid;grid-template-columns:1fr 1fr}.promotion{grid-template-columns:1fr}.center{min-height:650px}}@media(max-width:780px){header{align-items:flex-start;flex-direction:column}.brand{min-width:0}.connect{width:100%;min-width:0}.hero{padding:8px 8px 0}.growthTop{align-items:flex-start;flex-direction:column}.stages{grid-template-columns:1fr 1fr}.promotion{grid-template-columns:1fr}.baGrid{grid-template-columns:1fr}.baArrow{transform:rotate(90deg);height:28px}.layout{grid-template-columns:1fr;padding:8px}.left,.right{max-height:none}.center{min-height:620px}.right{display:block}.spaceHead{flex-wrap:wrap}.spaceHead input{max-width:none}.ruleText{font-size:20px}}
</style>
</head>
<body>
<header>
<div class="brand"><h1><span class="pulse"></span>The Logical Robot</h1><small>Living Logical Space · one intelligence, this page is only a manifested body</small></div>
<div class="statusbar"><span id="modePill" class="pill">connecting…</span><span id="versionPill" class="pill">space —</span><span class="pill">QCDS / Syntract</span><span id="runtimeDetail" class="pill hidden"></span></div>
<div id="connectBox" class="connect"><input id="endpoint" placeholder="https://runtime.example"><button onclick="connectRuntime()">Connect runtime</button></div>
</header>
<section class="hero">
<div class="growthHero">
<div class="growthTop"><div class="growthTitle"><div class="eyebrow">What matters</div><h2>INTELLIGENCE GROWTH</h2><p>The robot is not merely collecting text. Governed logic changes what Reality can resolve.</p></div><div class="growthActions"><button id="runOne" class="heroButton" onclick="runNextStep()">RUN NEXT FRONTIER STEP</button><button class="heroButton" onclick="toggleContinuous(true)">BUILD INTELLIGENCE CONTINUOUSLY</button><button onclick="sendSimple('pause')">PAUSE</button></div></div>
<div class="stages"><div class="stage"><span class="stageName">Observation / base</span><b id="gObserved">0</b><small>represented bindings</small></div><div class="stage"><span class="stageName">Candidate logic</span><b id="gCandidates">0</b><small>governance candidate records</small></div><div class="stage"><span class="stageName">Quarantined</span><b id="gQuarantined">0</b><small>candidate records held back</small></div><div class="stage"><span class="stageName">Promoted logic</span><b id="gPromoted">0</b><small>active governed rules</small></div></div>
<div class="flow">OBSERVATION → ORACLE GAP → CANDIDATE LOGIC → CHALLENGE / GOVERNANCE → <strong>PROMOTED LOGIC → REALITY RESOLVES MORE</strong></div>
<div class="promotion"><div id="promotionMain" class="promotionMain"><div id="promotionFlag" class="promotionFlag">Current intelligence state</div><div id="ruleText" class="noLogic">NO PROMOTED LOGIC YET</div><div id="promotionMeta" class="promotionMeta">Run the next represented frontier step or enable continuous intelligence. Human text and web sources remain input/evidence — not automatic truth.</div></div><div class="beforeAfter"><h3>Before → after intelligence</h3><div class="baGrid"><div class="ba"><label>Before latest logic</label><b id="beforeValue">unresolved</b><p id="beforeText">No derived capability from a new governed rule yet.</p></div><div class="baArrow">→</div><div class="ba after"><label>After promoted logic</label><b id="afterValue">waiting</b><p id="afterText">When logic is promoted, affected Reality bindings and newly resolved terms appear here.</p></div></div><div class="gainline" id="gainLine">Knowledge gain is measured from the resolved Reality view, not by counting downloaded text.</div></div></div>
</div>
</section>
<div class="layout">
<aside class="panel left"><div class="panelTitle">Robot control / I-O</div>
<div class="section"><h3>Reality</h3><div class="metrics"><div class="metric"><b id="mTerms">0</b><span>logical terms</span></div><div class="metric"><b id="mBindings">0</b><span>bindings</span></div><div class="metric"><b id="mRules">0</b><span>active rules</span></div><div class="metric"><b id="mFrontier">0</b><span>pending frontier</span></div></div></div>
<div class="section"><h3>Active modes</h3><div id="modes"></div><div class="actions" style="margin-top:8px"><button onclick="sendSimple('resume')">Resume</button><button onclick="sendSimple('pause')">Pause</button></div></div>
<div class="section"><h3>Input / event</h3><select id="action"><option value="dialogue">Dialogue</option><option value="investigate">Investigate</option><option value="explore_domain">Explore knowledge domain</option><option value="build_frontier">Build frontier around…</option><option value="visit_url">Go to web page</option></select><textarea id="text" placeholder="Ask, investigate, explore a domain, build frontier, or provide a URL…"></textarea><div class="row"><input id="priority" type="number" step="1" value="5" min="0" max="100"><button class="primary" onclick="submitInput()">SEND</button></div><div id="ioHint" class="notice">Input creates intent/evidence/frontier. It never becomes truth merely because a human or web page said it.</div></div>
<div class="section"><h3>Three different things</h3><div class="hint"><strong>Observation</strong> — what was seen/read.<br><strong>Candidate logic</strong> — a hypothesis that may explain it.<br><strong>Promoted logic</strong> — logic that survived the required challenge/governance path and is active in Reality.</div></div>
</aside>
<main class="panel center"><div class="spaceHead"><b>Living Logical Space</b><input id="search" placeholder="focus a represented term…" oninput="renderGraph()"><button onclick="resetView()">CENTER</button><span class="spacer"></span><span id="graphMeta" class="pill">0 nodes</span></div><div class="graphWrap"><svg id="graph" viewBox="-500 -350 1000 700"><g id="viewport"><g id="edges"></g><g id="nodes"></g></g></svg><div id="graphEmpty" class="graphEmpty">No represented Reality logic yet.<br>Run a frontier step and watch this space change.</div><div class="legend">● observed/base term &nbsp; <span style="color:#c6a4ff">● governed-rule term</span><br>Current projection of a logical space — not a required hierarchy or ontology.</div><div id="detail" class="detail"></div></div><div class="growthChart"><div class="growthChartHead">Reality growth history — base bindings and governed rules</div><svg id="growthChart" viewBox="0 0 1000 70" preserveAspectRatio="none"></svg></div></main>
<aside class="panel right"><div class="section"><h3>Frontier — what the robot may do next</h3><div id="frontier"><div class="empty">No frontier yet</div></div></div><div class="section"><h3>Discovery / reasoning timeline</h3><div id="timeline" class="timeline"></div></div></aside>
</div>
<script>
const STATIC_MODE=__QCDS_STATIC__;
let API=STATIC_MODE?'':location.origin,cursor=0,graphData={nodes:[],edges:[],growth_history:[],counts:{}},growthData={},previousNodes=new Set(),pan={x:0,y:0,s:1},dragging=false,last={x:0,y:0},liveHealth=false;
const demo={
 state:{modes:{dialogue:true,public_web:true,explore_domains:true,build_own_frontier:true,continuous_intelligence:false},frontier:{pending:1},paused:false},
 space:{version:'verified-build24-proof',counts:{logical_terms:8,bindings:8,active_rules:1},nodes:[{id:'france',label:'france',kind:'term',degree:3},{id:'paris',label:'paris',kind:'rule_term',degree:3},{id:'germany',label:'germany',kind:'term',degree:2},{id:'berlin',label:'berlin',kind:'term',degree:2},{id:'capital',label:'capital',kind:'term',degree:3},{id:'place',label:'place',kind:'term',degree:4}],edges:[{id:'1',source:'france',target:'place',kind:'binding'},{id:'2',source:'germany',target:'place',kind:'binding'},{id:'3',source:'germany',target:'berlin',kind:'binding'},{id:'4',source:'berlin',target:'capital',kind:'binding'},{id:'5',source:'france',target:'paris',kind:'rule'},{id:'6',source:'paris',target:'capital',kind:'binding'}],growth_history:[{snapshot_id:1,bindings:8,logical_terms:7,active_rules:0},{snapshot_id:2,bindings:8,logical_terms:8,active_rules:1}]},
 growth:{stage_counts:{observed_base_bindings:8,candidate_rule_records:12,quarantined_candidate_records:0,active_governed_rules:1},latest_promotion:{event:'GENESIS',rule_id:'build24-france-paris',version:1,match_terms:['france'],emit_terms:['paris'],rule_text:'france ⇒ paris',confidence:1,direct_matches:2,resolved_bindings_changed:2,new_resolved_term_instances:2,examples:[{binding_id:'country-france-1',before:['country-france-1','france'],after:['country-france-1','france','paris'],added:['paris']},{binding_id:'country-france-2',before:['country-france-2','france'],after:['country-france-2','france','paris'],added:['paris']}]},before_after:{resolved_bindings_changed:2,new_resolved_term_instances:2}},
 events:[{event_id:1,timestamp:'verified proof',event_type:'oracle_gap_detected',source:'qcds',payload:{rival_hypotheses:12}},{event_id:2,timestamp:'verified proof',event_type:'evidence_plan_created',source:'logical_robot',payload:{contexts:['france','germany']}},{event_id:3,timestamp:'verified proof',event_type:'public_web_observations',source:'logical_robot',payload:{sources:3,provider:'Wikipedia'}},{event_id:4,timestamp:'verified proof',event_type:'rule_promoted_to_reality',source:'qcds',payload:{rule:'france => paris',blast_fraction:0.25,override:false}},{event_id:5,timestamp:'verified proof',event_type:'knowledge_gain',source:'qcds',payload:{before:0,after:2}}],
 frontier:[{frontier_id:1,kind:'build_frontier',goal:'Continue from remaining uncertainty',status:'pending',priority:4}]
};
function apiUrl(path){return (API||'')+path}
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
async function getJson(path){const r=await fetch(apiUrl(path),{cache:'no-store'});if(!r.ok)throw new Error(path+' '+r.status);return r.json()}
async function postJson(path,body){const r=await fetch(apiUrl(path),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'request failed');return j}
function setConnection(mode,label,detail=''){modePill.className='pill '+mode;modePill.textContent=label;runtimeDetail.textContent=detail;runtimeDetail.classList.toggle('hidden',!detail);if(STATIC_MODE)connectBox.style.display=mode==='live'?'none':'flex';else connectBox.style.display='none'}
function connectRuntime(){let v=endpoint.value.trim().replace(/\/$/,'');if(!v)return;API=v;localStorage.setItem('qcds-runtime',v);cursor=0;refresh(true)}
function renderModes(state){modes.innerHTML='';const labels={dialogue:'Human dialogue',public_web:'Public web discovery',explore_domains:'Explore knowledge domains',build_own_frontier:'Build own frontier',continuous_intelligence:'Continuous intelligence'};for(const [k,v] of Object.entries(state.modes||{})){const d=document.createElement('label');d.className='mode';d.innerHTML='<span>'+esc(labels[k]||k)+'</span><input class="switch" type="checkbox" '+(v?'checked':'')+'>';d.querySelector('input').onchange=e=>setMode(k,e.target.checked);modes.appendChild(d)}}
async function setMode(mode,active){if(!API){ioHint.textContent='Connect a runtime to change live modes.';return}try{await postJson('/api/mode',{mode,active});ioHint.className='notice good';ioHint.textContent=(active?'Enabled ':'Disabled ')+mode.replaceAll('_',' ');await refresh()}catch(e){ioHint.className='notice warn';ioHint.textContent=e.message}}
async function toggleContinuous(active){await setMode('continuous_intelligence',active)}
async function sendSimple(kind){if(!API){ioHint.textContent='Connect a live runtime for control.';return}try{await postJson('/api/input',{kind,payload:{}});await refresh()}catch(e){ioHint.className='notice warn';ioHint.textContent=e.message}}
async function runNextStep(){if(!API){ioHint.textContent='Recorded proof is read-only. Open Codespaces or connect a runtime.';return}runOne.disabled=true;runOne.textContent='RUNNING LOGICAL STEP…';ioHint.className='notice';ioHint.textContent='The Logical Robot is processing the highest-priority represented frontier item…';try{const j=await postJson('/api/process-one',{});ioHint.className='notice good';ioHint.textContent=j.processed?'Frontier step completed. Reality/growth view refreshed.':'No pending frontier item.';await refresh(true)}catch(e){ioHint.className='notice warn';ioHint.textContent=e.message}finally{runOne.disabled=false;runOne.textContent='RUN NEXT FRONTIER STEP'}}
async function submitInput(){if(!API){ioHint.textContent='Recorded proof is read-only. Connect a live runtime.';return}const kind=action.value,raw=text.value.trim();const payload={text:raw,priority:Number(priority.value||5)};if(kind==='visit_url')payload.url=raw;try{const j=await postJson('/api/input',{kind,payload});ioHint.className='notice good';ioHint.textContent='Accepted · '+(j.frontier_id?'frontier #'+j.frontier_id:'event')+'. No automatic truth effect.';text.value='';await refresh()}catch(e){ioHint.className='notice warn';ioHint.textContent=e.message}}
function applyMetrics(space,state){mTerms.textContent=space.counts?.logical_terms||0;mBindings.textContent=space.counts?.bindings||0;mRules.textContent=space.counts?.active_rules||0;mFrontier.textContent=state.frontier?.pending??0}
function renderGrowthOverview(g){growthData=g||{};const c=g.stage_counts||{};gObserved.textContent=c.observed_base_bindings||0;gCandidates.textContent=c.candidate_rule_records||0;gQuarantined.textContent=c.quarantined_candidate_records||0;gPromoted.textContent=c.active_governed_rules||0;const p=g.latest_promotion;if(!p){promotionMain.className='promotionMain';promotionFlag.className='promotionFlag';promotionFlag.textContent='Current intelligence state';ruleText.className='noLogic';ruleText.textContent='NO PROMOTED LOGIC YET';promotionMeta.textContent='Run the next represented frontier step or enable continuous intelligence. The system must generate/test logic before this changes.';beforeValue.textContent='unresolved';beforeText.textContent='No latest governed rule to remove from the resolved view.';afterValue.textContent='waiting';afterText.textContent='A successful promotion will show its actual resolved effect here.';gainLine.textContent='Knowledge gain is measured from the resolved Reality view, not by counting downloaded text.';return}promotionMain.className='promotionMain good';promotionFlag.className='promotionFlag good';promotionFlag.textContent='✓ NEW LOGIC PROMOTED';ruleText.className='ruleText';const parts=(p.rule_text||'').split('⇒');ruleText.innerHTML=parts.length===2?esc(parts[0])+'<span class="arrow">⇒</span>'+esc(parts[1]):esc(p.rule_text||p.rule_id);promotionMeta.innerHTML='rule <b>'+esc(p.rule_id)+'</b> · v'+esc(p.version)+' · confidence '+esc(p.confidence)+'<br>direct base matches '+esc(p.direct_matches)+' · governed source '+esc(p.source_id);beforeValue.textContent='without rule';afterValue.textContent=(p.resolved_bindings_changed||0)+' bindings changed';const ex=(p.examples||[])[0];beforeText.textContent=ex?'Example '+ex.binding_id+': '+(ex.before||[]).join(' · '):'Counterfactual resolved view without this active rule.';afterText.textContent=ex?'Example '+ex.binding_id+': '+(ex.after||[]).join(' · '):'Resolved Reality with this governed rule active.';gainLine.innerHTML='<strong>+'+esc(p.new_resolved_term_instances||0)+' resolved term instances</strong> from this latest governed logic · '+esc(p.resolved_bindings_changed||0)+' Reality bindings affected.'}
function h32(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function position(node){const h=h32(node.id),ring=135+(h%4)*70,a=((h%10000)/10000)*Math.PI*2,bias=Math.min(80,(node.degree||0)*7);return{x:Math.cos(a)*(ring-bias),y:Math.sin(a)*(ring-bias)*.72}}
function renderGraph(){const ns=nodes,es=edges;ns.innerHTML='';es.innerHTML='';graphEmpty.style.display=graphData.nodes?.length?'none':'grid';const q=search.value.trim().toLowerCase(),pos={};(graphData.nodes||[]).forEach(n=>pos[n.id]=position(n));for(const e of graphData.edges||[]){if(!pos[e.source]||!pos[e.target])continue;const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',pos[e.source].x);l.setAttribute('y1',pos[e.source].y);l.setAttribute('x2',pos[e.target].x);l.setAttribute('y2',pos[e.target].y);l.setAttribute('class','edge '+(e.kind==='rule'?'rule':''));l.onclick=()=>showDetail(e);es.appendChild(l)}const current=new Set((graphData.nodes||[]).map(n=>n.id));for(const n of graphData.nodes||[]){const g=document.createElementNS('http://www.w3.org/2000/svg','g'),p=pos[n.id],r=5+Math.min(12,Math.sqrt(n.degree||1)*2);g.setAttribute('transform',`translate(${p.x} ${p.y})`);g.setAttribute('class','node '+((n.kind||'').includes('rule')?'rule ':'')+(!previousNodes.has(n.id)&&previousNodes.size?'new ':'')+(q&&n.label.toLowerCase().includes(q)?'focus':''));const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('r',r);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('y',r+12);t.textContent=n.label.length>24?n.label.slice(0,22)+'…':n.label;g.append(c,t);g.onclick=()=>showDetail(n);ns.appendChild(g)}previousNodes=current;graphMeta.textContent=(graphData.nodes||[]).length+' nodes · '+(graphData.edges||[]).length+' connections';versionPill.textContent='space '+(graphData.version||'—');applyView()}
function showDetail(v){detail.style.display='block';detail.innerHTML='<b>'+esc(v.label||v.kind||'logical element')+'</b><pre style="white-space:pre-wrap;color:#a9bfcd">'+esc(JSON.stringify(v,null,2))+'</pre>'}
function renderGrowthChart(){const s=growthChart;s.innerHTML='';const h=graphData.growth_history||[];if(!h.length)return;const maxB=Math.max(1,...h.map(x=>x.bindings||0)),maxR=Math.max(1,...h.map(x=>x.active_rules||0));const pts=h.map((x,i)=>`${i/(Math.max(1,h.length-1))*990+5},${64-(x.bindings||0)/maxB*54}`).join(' '),rpts=h.map((x,i)=>`${i/(Math.max(1,h.length-1))*990+5},${64-(x.active_rules||0)/maxR*54}`).join(' ');s.innerHTML='<polyline points="'+pts+'"/><polyline class="rules" points="'+rpts+'"/><text x="8" y="9">bindings '+maxB+'</text><text x="820" y="9">rules '+maxR+'</text>'}
function renderFrontier(items){frontier.innerHTML='';if(!items.length){frontier.innerHTML='<div class="empty">No represented frontier</div>';return}for(const x of items.slice(0,30)){const d=document.createElement('div');d.className='frontierItem';d.innerHTML='<div class="kind">#'+x.frontier_id+' · '+esc(x.kind)+'</div><div class="goal">'+esc(x.goal)+'</div><div class="state">'+esc(x.status)+' · priority '+esc(x.priority)+'</div>';frontier.appendChild(d)}}
function addEvents(items,reset=false){if(reset)timeline.innerHTML='';for(const e of items){cursor=Math.max(cursor,e.event_id||0);const d=document.createElement('div'),type=e.event_type||'event',warn=/await|conflict|quarant|blocked|error/.test(type),good=/promot|expand|knowledge|completed/.test(type),hot=/frontier_selected|oracle_gap|candidate/.test(type);d.className='event '+(warn?'warn':good?'good':hot?'hot':'');d.innerHTML='<div class="meta">#'+esc(e.event_id)+' · '+esc(e.timestamp)+' · '+esc(e.source)+'</div><b>'+esc(type)+'</b><pre>'+esc(JSON.stringify(e.payload||{},null,2))+'</pre>';timeline.prepend(d)}}
async function refresh(reset=false){if(!API){graphData=demo.space;renderModes(demo.state);renderFrontier(demo.frontier);addEvents(demo.events,true);applyMetrics(demo.space,demo.state);renderGrowthOverview(demo.growth);renderGraph();renderGrowthChart();setConnection('recorded','RECORDED VERIFIED PROOF');return}
 let healthOk=false;try{const h=await getJson('/api/health');healthOk=h.status==='ok'}catch(e){healthOk=false}
 if(!healthOk){if(STATIC_MODE){API='';setConnection('recorded','RUNTIME OFFLINE · RECORDED PROOF');return refresh(true)}setConnection('degraded','RUNTIME UNREACHABLE','main API health failed');return}
 liveHealth=true;setConnection('live','LIVE RUNTIME');let problems=[];
 const settled=await Promise.allSettled([getJson('/api/control'),getJson('/api/space'),getJson('/api/frontier'),getJson('/api/growth')]);
 const [sr,sp,fr,gr]=settled;if(sr.status==='fulfilled')renderModes(sr.value);else problems.push('control');if(sp.status==='fulfilled'){graphData=sp.value;renderGraph();renderGrowthChart()}else problems.push('space');if(fr.status==='fulfilled')renderFrontier(fr.value.frontier||[]);else problems.push('frontier');if(gr.status==='fulfilled')renderGrowthOverview(gr.value);else problems.push('growth');if(sr.status==='fulfilled'&&sp.status==='fulfilled')applyMetrics(sp.value,sr.value);
 try{const ev=await getJson('/api/events?after='+(reset?0:cursor));addEvents(ev.events||[],reset)}catch(e){problems.push('events')}
 if(problems.length)setConnection('degraded','LIVE · PARTIAL VIEW','retrying '+problems.join(', '));else setConnection('live','LIVE RUNTIME');}
function applyView(){viewport.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.s})`)}function resetView(){pan={x:0,y:0,s:1};applyView()}graph.addEventListener('wheel',e=>{e.preventDefault();pan.s=Math.max(.35,Math.min(3,pan.s*(e.deltaY<0?1.1:.91)));applyView()},{passive:false});graph.addEventListener('pointerdown',e=>{dragging=true;last={x:e.clientX,y:e.clientY};graph.setPointerCapture(e.pointerId)});graph.addEventListener('pointermove',e=>{if(!dragging)return;pan.x+=(e.clientX-last.x)/pan.s;pan.y+=(e.clientY-last.y)/pan.s;last={x:e.clientX,y:e.clientY};applyView()});graph.addEventListener('pointerup',()=>dragging=false);
if(STATIC_MODE){const saved=localStorage.getItem('qcds-runtime');if(saved){endpoint.value=saved;API=saved}else API='';connectBox.style.display='flex'}else{API=location.origin;connectBox.style.display='none'}refresh(true);setInterval(()=>refresh(false),1500);
</script>
</body></html>'''


def living_robot_html(*, static_mode: bool = False) -> str:
    return _HTML.replace("__QCDS_STATIC__", "true" if static_mode else "false")


def export_static(path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(living_robot_html(static_mode=True), encoding="utf-8")
    return target


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export the static GitHub Pages manifestation of the Logical Robot.")
    parser.add_argument("--export", required=True, help="Output HTML path")
    args = parser.parse_args(argv)
    export_static(args.export)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
