from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence


_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#07101a">
<title>The Logical Robot — Living Logical Space</title>
<style>
:root{color-scheme:dark;--bg:#07101a;--panel:#0b1724;--panel2:#0d1c2b;--line:#233e54;--text:#edf6ff;--muted:#8da8bb;--good:#7ee0a3;--warn:#f1bc6c;--hot:#f58aa4;--accent:#73c8ff;--rule:#c6a4ff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text)}body{background:radial-gradient(circle at 13% -5%,#153650 0,#08121d 34%,#050a10 75%);overflow-x:hidden}
header{display:flex;align-items:center;gap:16px;padding:18px 22px;border-bottom:1px solid #1d3549;background:#07121dda;backdrop-filter:blur(12px);position:sticky;top:0;z-index:20}.brand{min-width:255px}.brand h1{font-size:19px;margin:0}.brand small{color:var(--muted)}.pulse{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--good);box-shadow:0 0 18px var(--good);margin-right:8px}.statusbar{display:flex;gap:8px;flex:1;flex-wrap:wrap}.pill{font-size:11px;padding:6px 9px;border:1px solid #2b475e;border-radius:999px;background:#0d1d2a;color:#aac0cf}.pill.live{border-color:#397a58;color:#a8f1c2}.pill.recorded{border-color:#765c32;color:#f5d18e}.connect{display:flex;gap:6px;min-width:300px}.connect input{min-width:210px}
.layout{display:grid;grid-template-columns:270px minmax(500px,1fr) 340px;gap:12px;padding:12px;height:calc(100vh - 73px)}.panel{border:1px solid var(--line);background:#091724e9;border-radius:15px;overflow:hidden;box-shadow:0 16px 45px #0005}.panelTitle{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#94adbf;padding:13px 14px 10px;border-bottom:1px solid #1d3447}.left,.right{overflow:auto}.section{padding:12px 13px;border-bottom:1px solid #162c3e}.section:last-child{border:0}.section h3{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:#839fb2;margin:0 0 9px}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:7px}.metric{background:#0c2030;border:1px solid #244359;border-radius:10px;padding:10px}.metric b{font-size:20px;display:block}.metric span{font-size:9px;color:#91a9ba;text-transform:uppercase;letter-spacing:.04em}.mode{display:flex;align-items:center;justify-content:space-between;padding:7px 0;border-bottom:1px solid #142a39;font-size:12px}.mode:last-child{border:0}.switch{appearance:none;width:34px;height:18px;background:#293b48;border-radius:20px;position:relative;cursor:pointer}.switch:after{content:"";position:absolute;width:14px;height:14px;left:2px;top:2px;border-radius:50%;background:#8093a0;transition:.15s}.switch:checked{background:#265e43}.switch:checked:after{left:18px;background:#aaf4c4}.actions{display:flex;gap:6px;flex-wrap:wrap}.btn,button{border:1px solid #31516a;background:#102536;color:#eaf6ff;border-radius:9px;padding:8px 10px;font-weight:650;font-size:11px;cursor:pointer}.btn.primary,button.primary{background:#d9f6e3;color:#082016;border-color:#d9f6e3}.btn.warn{border-color:#765d33;color:#f0ca86}.btn:hover,button:hover{filter:brightness(1.12)}select,input,textarea{width:100%;background:#07131e;color:#eaf6ff;border:1px solid #2d4c63;border-radius:9px;padding:9px;font:inherit;font-size:12px}textarea{min-height:82px;resize:vertical}.row{display:flex;gap:7px}.row>*{flex:1}.hint{font-size:10px;line-height:1.5;color:#819bad;margin-top:7px}.hidden{display:none!important}
.center{display:grid;grid-template-rows:auto minmax(0,1fr) 115px}.spaceHead{display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid #1c3548}.spaceHead input{max-width:260px}.spaceHead .spacer{flex:1}.graphWrap{position:relative;min-height:0;background:radial-gradient(circle at center,#0b2030 0,#07131d 48%,#050c12 100%)}#graph{width:100%;height:100%;display:block;touch-action:none}.edge{stroke:#375466;stroke-opacity:.42;stroke-width:1}.edge.rule{stroke:var(--rule);stroke-opacity:.72;stroke-width:1.8}.node circle{fill:#173b51;stroke:#75b9de;stroke-width:1.2}.node.rule circle{fill:#33284a;stroke:#c3a6f5}.node.new circle{stroke:var(--good);stroke-width:3;filter:drop-shadow(0 0 5px #7ee0a3)}.node.focus circle{stroke:#fff4ac;stroke-width:3}.node text{fill:#d6e8f3;font-size:9px;pointer-events:none;text-anchor:middle}.legend{position:absolute;left:10px;bottom:10px;background:#07131ed9;border:1px solid #274357;border-radius:9px;padding:7px 9px;font-size:9px;color:#9ab0bf}.detail{position:absolute;right:10px;top:10px;max-width:280px;background:#07131eef;border:1px solid #31526a;border-radius:10px;padding:10px;font-size:10px;line-height:1.45;display:none}.growth{padding:8px 12px;border-top:1px solid #1c3548}.growthHead{font-size:10px;color:#8ba6b8;margin-bottom:3px}.growth svg{width:100%;height:76px}.growth polyline{fill:none;stroke:#73c8ff;stroke-width:2}.growth .rules{stroke:#c6a4ff}.growth text{fill:#7390a5;font-size:8px}
.timeline{display:flex;flex-direction:column;gap:7px}.event{border-left:3px solid #456b83;background:#0a1d2a;border-radius:8px;padding:8px}.event.good{border-color:var(--good)}.event.warn{border-color:var(--warn)}.event.hot{border-color:var(--hot)}.event .meta{font-size:9px;color:#6f8da2}.event b{font-size:11px}.event pre{font-size:9px;color:#9db5c5;white-space:pre-wrap;word-break:break-word;margin:4px 0 0;max-height:110px;overflow:auto}.frontierItem{padding:8px;border:1px solid #244157;background:#0b1d2a;border-radius:9px;margin-bottom:6px}.frontierItem .kind{font-size:9px;text-transform:uppercase;color:#8fa9bb}.frontierItem .goal{font-size:11px;margin-top:3px}.frontierItem .state{font-size:9px;color:#7ee0a3;margin-top:4px}.empty{padding:12px;color:#718da1;font-size:11px;text-align:center}
@media(max-width:1150px){.layout{grid-template-columns:245px 1fr}.right{grid-column:1/-1;height:330px}.layout{height:auto}.center{height:760px}.right{display:grid;grid-template-columns:1fr 1fr}}@media(max-width:760px){header{align-items:flex-start;flex-direction:column}.connect{width:100%;min-width:0}.layout{grid-template-columns:1fr}.center{height:640px}.right{display:block;height:auto}.brand{min-width:0}}
</style>
</head>
<body>
<header><div class="brand"><h1><span class="pulse"></span>The Logical Robot</h1><small>Living Logical Space · same intelligence, one manifested body</small></div><div class="statusbar"><span id="modePill" class="pill">connecting…</span><span id="versionPill" class="pill">space —</span><span class="pill">QCDS / Syntract</span></div><div id="connectBox" class="connect"><input id="endpoint" placeholder="https://runtime.example"><button onclick="connectRuntime()">Connect runtime</button></div></header>
<div class="layout">
<aside class="panel left"><div class="panelTitle">Robot control / I-O</div>
<div class="section"><h3>Reality</h3><div class="metrics"><div class="metric"><b id="mTerms">0</b><span>logical terms</span></div><div class="metric"><b id="mBindings">0</b><span>bindings</span></div><div class="metric"><b id="mRules">0</b><span>active rules</span></div><div class="metric"><b id="mFrontier">0</b><span>frontier</span></div></div></div>
<div class="section"><h3>Active modes</h3><div id="modes"></div><div class="actions" style="margin-top:9px"><button class="primary" onclick="toggleContinuous(true)">Build intelligence continuously</button><button onclick="sendSimple('pause')">Pause</button><button onclick="sendSimple('resume')">Resume</button></div></div>
<div class="section"><h3>Input / event</h3><select id="action"><option value="dialogue">Dialogue</option><option value="investigate">Investigate</option><option value="explore_domain">Explore knowledge domain</option><option value="build_frontier">Build frontier around…</option><option value="visit_url">Go to web page</option></select><textarea id="text" placeholder="Ask, direct, explore or provide a URL…"></textarea><div class="row"><input id="priority" type="number" step="1" value="5" min="0" max="100"><button class="primary" onclick="submitInput()">Send</button></div><div id="ioHint" class="hint">Ordinary text is an event/intent, never automatic truth.</div></div>
<div class="section"><h3>Runtime</h3><div class="hint">Local: <code>qcds-live</code><br>Remote: open the repository in Codespaces. The forwarded port runs this same body against the same Python runtime.</div></div></aside>
<main class="panel center"><div class="spaceHead"><b style="font-size:12px">Living Logical Space</b><input id="search" placeholder="focus term…" oninput="renderGraph()"><button onclick="resetView()">Center</button><span class="spacer"></span><span id="graphMeta" class="pill">0 nodes</span></div><div class="graphWrap"><svg id="graph" viewBox="-500 -350 1000 700"><g id="viewport"><g id="edges"></g><g id="nodes"></g></g></svg><div class="legend">● observed term &nbsp; <span style="color:#c6a4ff">● governed-rule term</span><br>Projection only — not a hierarchy/ontology</div><div id="detail" class="detail"></div></div><div class="growth"><div class="growthHead">Reality growth history — bindings and governed rules</div><svg id="growth" viewBox="0 0 1000 75" preserveAspectRatio="none"></svg></div></main>
<aside class="panel right"><div class="section"><h3>Frontier</h3><div id="frontier"><div class="empty">No frontier yet</div></div></div><div class="section"><h3>Discovery timeline</h3><div id="timeline" class="timeline"></div></div></aside>
</div>
<script>
const STATIC_MODE=__QCDS_STATIC__;
let API=STATIC_MODE?'':location.origin, cursor=0, graphData={nodes:[],edges:[],growth_history:[],counts:{}}, previousNodes=new Set(), pan={x:0,y:0,s:1}, dragging=false,last={x:0,y:0};
const demo={state:{modes:{dialogue:true,public_web:true,explore_domains:true,build_own_frontier:true,continuous_intelligence:false},frontier:{pending:2},paused:false},space:{version:'verified-build24-proof',counts:{logical_terms:8,bindings:8,active_rules:1},nodes:[{id:'france',label:'france',kind:'term',degree:3},{id:'paris',label:'paris',kind:'rule_term',degree:3},{id:'germany',label:'germany',kind:'term',degree:2},{id:'berlin',label:'berlin',kind:'term',degree:2},{id:'capital',label:'capital',kind:'term',degree:3},{id:'place',label:'place',kind:'term',degree:4}],edges:[{id:'1',source:'france',target:'place',kind:'binding'},{id:'2',source:'germany',target:'place',kind:'binding'},{id:'3',source:'germany',target:'berlin',kind:'binding'},{id:'4',source:'berlin',target:'capital',kind:'binding'},{id:'5',source:'france',target:'paris',kind:'rule'},{id:'6',source:'paris',target:'capital',kind:'binding'}],growth_history:[{snapshot_id:1,bindings:8,logical_terms:7,active_rules:0},{snapshot_id:2,bindings:8,logical_terms:8,active_rules:1}]},events:[{event_id:1,timestamp:'verified proof',event_type:'oracle_gap_detected',source:'qcds',payload:{rival_hypotheses:12}},{event_id:2,timestamp:'verified proof',event_type:'evidence_plan_created',source:'logical_robot',payload:{contexts:['france','germany']}},{event_id:3,timestamp:'verified proof',event_type:'public_web_observations',source:'logical_robot',payload:{sources:3,provider:'Wikipedia'}},{event_id:4,timestamp:'verified proof',event_type:'rule_promoted_to_reality',source:'qcds',payload:{rule:'france => paris',blast_fraction:0.25,override:false}},{event_id:5,timestamp:'verified proof',event_type:'knowledge_gain',source:'qcds',payload:{before:0,after:2}}],frontier:[{frontier_id:1,kind:'investigate',goal:'France / capital',status:'completed',priority:10},{frontier_id:2,kind:'build_frontier',goal:'Continue from remaining uncertainty',status:'pending',priority:4}]};
function apiUrl(path){return (API||'')+path}function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function setConnection(live,label){modePill.className='pill '+(live?'live':'recorded');modePill.textContent=label;connectBox.style.display=live&&!STATIC_MODE?'none':'flex'}
async function getJson(path){const r=await fetch(apiUrl(path),{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}async function postJson(path,body){const r=await fetch(apiUrl(path),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'request failed');return j}
function connectRuntime(){let v=endpoint.value.trim().replace(/\/$/,'');if(!v)return;API=v;localStorage.setItem('qcds-runtime',v);cursor=0;refresh(true)}
function renderModes(state){modes.innerHTML='';const labels={dialogue:'Human dialogue',public_web:'Public web discovery',explore_domains:'Explore knowledge domains',build_own_frontier:'Build own frontier',continuous_intelligence:'Continuous intelligence'};for(const [k,v] of Object.entries(state.modes||{})){const d=document.createElement('label');d.className='mode';d.innerHTML='<span>'+esc(labels[k]||k)+'</span><input class="switch" type="checkbox" '+(v?'checked':'')+'>';d.querySelector('input').onchange=e=>setMode(k,e.target.checked);modes.appendChild(d)}}
async function setMode(mode,active){if(!API){ioHint.textContent='Connect a runtime to change live modes.';return}try{await postJson('/api/mode',{mode,active});await refresh()}catch(e){ioHint.textContent=e.message}}
async function toggleContinuous(active){await setMode('continuous_intelligence',active)}async function sendSimple(kind){if(!API){ioHint.textContent='Connect a runtime for control.';return}try{await postJson('/api/input',{kind,payload:{}});await refresh()}catch(e){ioHint.textContent=e.message}}
async function submitInput(){if(!API){ioHint.textContent='Recorded proof is read-only. Connect a live runtime.';return}const kind=action.value,raw=text.value.trim();const payload={text:raw,priority:Number(priority.value||5)};if(kind==='visit_url')payload.url=raw;try{const j=await postJson('/api/input',{kind,payload});ioHint.textContent='accepted · '+(j.frontier_id?'frontier #'+j.frontier_id:'event');text.value='';await refresh()}catch(e){ioHint.textContent=e.message}}
function h32(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function position(node,i,n){const h=h32(node.id), ring=135+(h%4)*70, a=((h%10000)/10000)*Math.PI*2, bias=Math.min(80,(node.degree||0)*7);return{x:Math.cos(a)*(ring-bias),y:Math.sin(a)*(ring-bias)*.72}}
function renderGraph(){const ns=nodes,es=edges,detailBox=detail;ns.innerHTML='';es.innerHTML='';const q=search.value.trim().toLowerCase(),pos={};graphData.nodes.forEach((n,i)=>pos[n.id]=position(n,i,graphData.nodes.length));for(const e of graphData.edges){if(!pos[e.source]||!pos[e.target])continue;const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',pos[e.source].x);l.setAttribute('y1',pos[e.source].y);l.setAttribute('x2',pos[e.target].x);l.setAttribute('y2',pos[e.target].y);l.setAttribute('class','edge '+(e.kind==='rule'?'rule':''));l.onclick=()=>showDetail(e);es.appendChild(l)}const current=new Set(graphData.nodes.map(n=>n.id));for(const n of graphData.nodes){const g=document.createElementNS('http://www.w3.org/2000/svg','g'),p=pos[n.id],r=5+Math.min(12,Math.sqrt(n.degree||1)*2);g.setAttribute('transform',`translate(${p.x} ${p.y})`);g.setAttribute('class','node '+((n.kind||'').includes('rule')?'rule ':'')+(!previousNodes.has(n.id)&&previousNodes.size?'new ':'')+(q&&n.label.toLowerCase().includes(q)?'focus':''));const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('r',r);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('y',r+12);t.textContent=n.label.length>24?n.label.slice(0,22)+'…':n.label;g.append(c,t);g.onclick=()=>showDetail(n);ns.appendChild(g)}previousNodes=current;graphMeta.textContent=graphData.nodes.length+' nodes · '+graphData.edges.length+' connections';versionPill.textContent='space '+(graphData.version||'—');applyView()}
function showDetail(v){detail.style.display='block';detail.innerHTML='<b>'+esc(v.label||v.kind||'logical element')+'</b><pre style="white-space:pre-wrap;color:#a9bfcd">'+esc(JSON.stringify(v,null,2))+'</pre>'}
function renderGrowth(){const s=growth;s.innerHTML='';const h=graphData.growth_history||[];if(!h.length)return;const maxB=Math.max(1,...h.map(x=>x.bindings||0)),maxR=Math.max(1,...h.map(x=>x.active_rules||0));const pts=h.map((x,i)=>`${i/(Math.max(1,h.length-1))*990+5},${68-(x.bindings||0)/maxB*58}`).join(' '),rpts=h.map((x,i)=>`${i/(Math.max(1,h.length-1))*990+5},${68-(x.active_rules||0)/maxR*58}`).join(' ');s.innerHTML='<polyline points="'+pts+'"/><polyline class="rules" points="'+rpts+'"/><text x="8" y="10">bindings '+maxB+'</text><text x="820" y="10">rules '+maxR+'</text>'}
function renderFrontier(items){frontier.innerHTML='';if(!items.length){frontier.innerHTML='<div class="empty">No represented frontier</div>';return}for(const x of items.slice(0,30)){const d=document.createElement('div');d.className='frontierItem';d.innerHTML='<div class="kind">#'+x.frontier_id+' · '+esc(x.kind)+'</div><div class="goal">'+esc(x.goal)+'</div><div class="state">'+esc(x.status)+' · priority '+esc(x.priority)+'</div>';frontier.appendChild(d)}}
function addEvents(items,reset=false){if(reset)timeline.innerHTML='';for(const e of items){cursor=Math.max(cursor,e.event_id||0);const d=document.createElement('div'),type=e.event_type||'event',warn=/await|conflict|quarant|blocked|error/.test(type),good=/promot|expand|knowledge|completed/.test(type),hot=/frontier_selected|oracle_gap/.test(type);d.className='event '+(warn?'warn':good?'good':hot?'hot':'');d.innerHTML='<div class="meta">#'+esc(e.event_id)+' · '+esc(e.timestamp)+' · '+esc(e.source)+'</div><b>'+esc(type)+'</b><pre>'+esc(JSON.stringify(e.payload||{},null,2))+'</pre>';timeline.prepend(d)}}
function applyMetrics(space,state){mTerms.textContent=space.counts?.logical_terms||0;mBindings.textContent=space.counts?.bindings||0;mRules.textContent=space.counts?.active_rules||0;mFrontier.textContent=state.frontier?.pending??0}
async function refresh(reset=false){if(!API){graphData=demo.space;renderModes(demo.state);renderFrontier(demo.frontier);addEvents(demo.events,true);applyMetrics(demo.space,demo.state);renderGraph();renderGrowth();setConnection(false,'RECORDED VERIFIED PROOF');return}try{const [state,space,f]=await Promise.all([getJson('/api/control'),getJson('/api/space'),getJson('/api/frontier')]);graphData=space;renderModes(state);renderFrontier(f.frontier||[]);applyMetrics(space,state);renderGraph();renderGrowth();const ev=await getJson('/api/events?after='+(reset?0:cursor));addEvents(ev.events||[],reset);setConnection(true,'LIVE RUNTIME')}catch(e){if(STATIC_MODE){API='';setConnection(false,'RUNTIME OFFLINE · RECORDED PROOF');refresh(true)}else setConnection(false,'RUNTIME ERROR')}}
function applyView(){viewport.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.s})`)}function resetView(){pan={x:0,y:0,s:1};applyView()}graph.addEventListener('wheel',e=>{e.preventDefault();pan.s=Math.max(.35,Math.min(3,pan.s*(e.deltaY<0?1.1:.91)));applyView()},{passive:false});graph.addEventListener('pointerdown',e=>{dragging=true;last={x:e.clientX,y:e.clientY};graph.setPointerCapture(e.pointerId)});graph.addEventListener('pointermove',e=>{if(!dragging)return;pan.x+=(e.clientX-last.x)/pan.s;pan.y+=(e.clientY-last.y)/pan.s;last={x:e.clientX,y:e.clientY};applyView()});graph.addEventListener('pointerup',()=>dragging=false);
if(STATIC_MODE){const saved=localStorage.getItem('qcds-runtime');if(saved){endpoint.value=saved;API=saved}else API=''}else connectBox.style.display='none';refresh(true);setInterval(()=>refresh(false),1500);
</script>
</body></html>'''


def living_robot_html(*, static_mode: bool = False) -> str:
    return _HTML.replace("__QCDS_STATIC__", "true" if static_mode else "false")


def export_static(path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(living_robot_html(static_mode=True), encoding="utf-8")
    return target


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export the static GitHub Pages manifestation of the Logical Robot.")
    parser.add_argument("--export", required=True, help="Output HTML path")
    args = parser.parse_args(argv)
    export_static(args.export)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
