// QCDS by Patrik Sundblom. Contributor: ChatGPT (OpenAI). LICENSE.md.
import { STARTERS } from './workspace.mjs?v=1.0.1';
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=['Goal','Route','Control','Bypass','Proof'];
const date = value => new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(value));

export function homeView({project,caseId,question,model,cases,archived,icon}) {
  const own=Object.entries(cases).filter(([id,p])=>(!p.example||id.startsWith("case-"))&&!archived.includes(id));
  const unknown=Object.values(project.input.flags).filter(v=>v===null).length;
  const liveRecords=model.findings.reduce((n,f)=>n+f.records.length,0);
  return `<div class="consumer-home"><section class="consumer-hero"><div class="consumer-hero-copy"><span class="eyebrow">Q★ SECURITY · YOUR PERSONAL WORKSPACE</span><h1>Understand the risk.<br><span>Know your next move.</span></h1><p>Turn a security worry into a clear investigation, practical checks and a report you can use.</p><button class="button primary" data-action="new">${icon('plus')} Start an investigation</button><a class="text-link" href="#examples">Try a complete example ${icon('arrow')}</a></div><div class="consumer-orbit" aria-hidden="true"><span class="orbit-ring one"></span><span class="orbit-ring two"></span><span class="orbit-core">Q<span>★</span></span><span class="orbit-caption">QUESTION · EXPLORE · VERIFY</span></div></section>
    <div class="consumer-trust"><span>${icon('shield')} Saved on your device</span><span>${icon('check')} No account required</span><button data-app-install class="text-button">Install app ↗</button><span data-offline-status></span></div>
    <section class="consumer-resume"><div class="consumer-section-title"><span class="eyebrow">${project.example?'YOUR PRACTICE CASE':'PICK UP WHERE YOU LEFT OFF'}</span><span class="consumer-tag">${project.example?'Worked example':'Your investigation'}</span></div><h2>${esc(project.input.name)}</h2><p>${esc(project.input.attackerGoal || 'Start by naming what you want to protect.')}</p><div class="consumer-step-track" aria-label="Current position: step ${question} of 5">${steps.map((step,i)=>`<span class="${i+1===question?'current':i+1<question?'visited':''}"><b>${i+1}</b>${step}</span>`).join('')}</div><div class="consumer-resume-bottom"><div><b>Step ${question} of 5 · ${steps[question-1]}</b><small>Your place in the investigation, not a security score.</small></div><button class="button primary" data-consumer-open="${esc(caseId)}">Continue investigation ${icon('arrow')}</button></div></section>
    <section class="consumer-overview" aria-label="Current investigation overview"><a href="#system"><b>${unknown}</b><span>Facts to clarify</span><small>Keep ? when you are unsure</small></a><a href="#findings"><b>${model.findings.length+model.pending.length}</b><span>Paths to review</span><small>Questions worth following</small></a><a href="#report"><b>${liveRecords}</b><span>Current observations</span><small>${project.example?'Synthetic example evidence':'Bound to the current scope'}</small></a></section>
    <section class="consumer-shortcuts"><a href="#cases">${icon('grid')}<div><h3>My investigations</h3><p>${own.length} saved personal ${own.length===1?'case':'cases'}. Keep each system separate.</p></div>${icon('arrow')}</a><a href="#report">${icon('report')}<div><h3>Build my report</h3><p>Findings, evidence, next actions and illustrated PDF.</p></div>${icon('arrow')}</a></section>
    <details class="consumer-lab"><summary>${icon('layers')} Explore the QCDS engine</summary><p>Follow dimensions, compare security perspectives and simulate ideal or noisy Grover circuits.</p><button class="button" data-open-logical>Run dimensional inference ↗</button><a class="text-link" href="./glasswing.html">Project Glasswing ↗</a></details><p class="consumer-footnote">Q Security helps you investigate possible attack paths. Device scanning and automatic security certification are outside this app’s scope.</p></div>`;
}

export function casesView({cases,places,archived,caseId,icon}) {
  const entries=Object.entries(cases).filter(([id,p])=>!p.example||id.startsWith("case-")).sort((a,b)=>new Date(b[1].updatedAt)-new Date(a[1].updatedAt));
  function card([id,p],isArchived=false){const step=places[id]?.question||1;return `<article class="consumer-case"><div class="consumer-case-icon">${icon('shield')}</div><div class="consumer-case-copy"><span class="eyebrow">${isArchived?'ARCHIVED':id===caseId?'CURRENT CASE':`STEP ${step} OF 5 · ${steps[step-1].toUpperCase()}`}</span><h2>${esc(p.input.name)}</h2><p>${esc(p.input.attackerGoal||'No goal added yet.')}</p><small>Saved ${date(p.updatedAt)} · ${p.evidence.length} observations</small></div><div class="consumer-case-actions"><button class="button primary" data-consumer-${isArchived?'restore':'open'}="${id}">${isArchived?'Restore':'Open'} ${icon('arrow')}</button><button class="text-button" data-consumer-copy="${id}">Make a copy</button>${!isArchived&&id!==caseId?`<button class="text-button" data-consumer-archive="${id}">Archive</button>`:''}</div></article>`;}
  return `<section class="consumer-page-heading"><span class="eyebrow">YOUR SPACE</span><h1>My investigations</h1><p>One system per case. Your questions, observations and actions stay together.</p><div class="consumer-actions"><button class="button primary" data-action="new">${icon('plus')} New investigation</button><button class="button" data-action="import">${icon('download')} Import a project</button><button class="button" data-consumer-backup>Back up all cases</button></div></section><div class="consumer-case-list">${entries.filter(([id])=>!archived.includes(id)).map(x=>card(x)).join('')||`<section class="consumer-empty"><span class="brand-mark">Q★</span><h2>Your first investigation starts with one question.</h2><p>Choose something you use, describe what worries you, and work through five clear steps.</p><button class="button primary" data-action="new">Start my first case ${icon('arrow')}</button><a class="text-link" href="#examples">Learn with a worked example</a></section>`}</div>${entries.some(([id])=>archived.includes(id))?`<details class="consumer-archive"><summary>Archived cases · ${archived.length}</summary>${entries.filter(([id])=>archived.includes(id)).map(x=>card(x,true)).join('')}</details>`:''}<p class="consumer-footnote">Cases are stored in this browser or app, not in a cloud account. Export a backup before moving devices or clearing app data.</p>`;
}

export function newCaseMarkup(icon) {
  return `<div class="dialog-head"><div><span class="eyebrow">NEW INVESTIGATION</span><h2 id="new-case-title">What would you like to protect?</h2></div><button class="icon-button" data-close-new-case aria-label="Close new investigation">${icon('close')}</button></div><form id="consumer-new-case-form" class="consumer-new-form"><fieldset><legend>Choose a starting point</legend><div class="consumer-starters">${STARTERS.map((s,i)=>`<label class="consumer-starter"><input type="radio" name="starter" value="${s.id}" ${i===0?'checked':''}><span>${icon(s.icon)}<b>${s.name}</b><small>${s.description}</small></span></label>`).join('')}</div></fieldset><label>Name your investigation<input name="name" required maxlength="120" placeholder="For example: Our family accounts" autocomplete="off"></label><label>What does this system do?<textarea name="description" rows="2" maxlength="5000" placeholder="A sentence or two is enough. You can add detail later."></textarea></label><p class="small muted">We’ll suggest a starting goal. Facts remain unknown until you review them. Your other investigations stay saved.</p><div class="consumer-actions"><button class="button primary" type="submit">Create investigation ${icon('arrow')}</button><button class="button" type="button" data-close-new-case>Cancel</button></div></form>`;
}

export function consumerNav({route,question,icon,investigationHref}) {
  const items=[['home','Home','grid','#home'],['cases','My cases','shield','#cases'],['investigate','Investigate','trace',investigationHref(question)],['report','Report','report','#report']];
  return `<nav class="consumer-bottom-nav" aria-label="Main app navigation">${items.map(([id,label,ic,url])=>`<a href="${url}" ${route===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></a>`).join('')}</nav>`;
}
